#ifndef GLOBALS_H
#define GLOBALS_H

#define INPUT_FILE "input.txt"
#define INPUT_SIZE 32768
#define INPUT_LINE_SIZE 128

#define NODE_SPACE_SIZE 17576
#define NODE_NULL NODE_SPACE_SIZE
#define NODE_MAX_CONNECTIONS 8

#endif
